name: github-pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build storybook
        run: yarn build-storybook -o ./dist/storybook
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
